### ISSUE TITLE
Not showing which view is broken

### ISSUE THREAD

**Issue by sks444** [mgrp/django-distill#10]
It shows the exception message but doesn't say which view had the exception.

**Comment by sks444** [comment]
e.g:  if there is some problem with a view, it shows the error:
```
CommandError: Failed to render view: 'total_count'
```
There was a problem in a line which includes `total_count`, it's not a view name.
Maybe the more appropriate error would be:
```
CommandError: Failed to render view: 'viewname'
A problem with the line `line no: exception message`
```

**Comment by meeb** [comment]
Hi sks444,

Thanks for the issue and sorry for taking ages to respond. I'm relatively happy with how verbose the error messages are at the moment, it should display a full trace of the issue which includes the line numbers which make finding where the error occurred pretty easy.

If you want to submit a pull request for more verbose errors if you would find them helpful I'd be happy to review it.

Cheers.
